fixtures:
  symlinks:
    contrail: "#{source_dir}"
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "2.6.0"
    sysctl:
      repo: https://github.com/duritong/puppet-sysctl
      ref: 3b027e816818f2c1086075038ac9b4af1cadbc24
